name: 🚀 Deploy Backend & Frontend to OVH

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📦 Deploy to OVH via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🚀 Upload to OVH (everything except ignored)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ 
          server-dir: /
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/docs/**
            **/database/**  # À inclure si tu veux la charger manuellement
            **/.env
            **/README.md
