name: 🚀 Deploy to OVH FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📦 Déploiement FTP OVH
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: 🚀 Déploiement FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ 
          server-dir: /www/public/
